### ISSUE TITLE
Broken zip

### ISSUE THREAD

**Issue by gerroon** [abbruzze/kernal64#1]
aria2c https://github.com/abbruzze/kernal64/tree/master/Kernal64/dist/kernal64_install.zip

Archive:  kernal64_install.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of kernal64_install.zip or

**Comment by abbruzze** [comment]
Hi and thanks for your mail.
Check the way you downloaded the zip: use the download button in the page (on the left).
I tried myself and it works properly.
