### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by rmoritz** [abbruzze/kernal64#10]
Hi,

sorry for the n00b question, but I've never programmed in Scala before and in general don't know the Java ecosystem very well.

So what's the quickest, most straightforward way to build the code on Linux (want to try out the Beamracer branch)?

Cheers,
Ralph

**Comment by ritschwumm** [comment]
what i can glean from the project:

the entry point to the build seems to be https://github.com/abbruzze/kernal64/blob/master/Kernal64/build/build.xml, which is used by [ant](https://ant.apache.org/) (a build tool a lot of people used for java apps in the old days before more modern alternatives became available).

with ant installed, `ant -f build/build.xml` run in the project base directory seems to build things then. i'm not sure whether there's anything else that needs to be done after.

**Comment by rmoritz** [comment]
Thanks, I'll install ant and give that a try! :+1:

**Comment by abbruzze** [comment]
> what i can glean from the project:
> 
> the entry point to the build seems to be https://github.com/abbruzze/kernal64/blob/master/Kernal64/build/build.xml, which is used by [ant](https://ant.apache.org/) (a build tool a lot of people used for java apps in the old days before more modern alternatives became available).
> 
> with ant installed, running `ant -f build/build.xml` in the project base directory seems to build things. i'm not sure whether there's anything else that needs to be done afterwards.
> 
> with `ant -p -f build/build.xml` you can check which targets are defined in the build.xml and then run e.g. `ant -f build/build.xml deploy`.

You're right about ant.
But when the project is simple, without any special dependency, the old (but still effective) ant is my best choice.
Thanks for your help.

Anyway, I'm going to merge the BeamRacer branch with master soon together with a lot of new feature/fix and a whole new vrey powerful assembler.
