### ISSUE TITLE
official support in the VICE testsuite

### ISSUE THREAD

**Issue by mrdudz** [abbruzze/kernal64#12]
Hy!

I stumbled about your repo and noticed you already hacked up support for the VICE testbench... very nice :) I have now merged your files, and added some more things. I have also made a full testrun, see

https://vice-emu.pokefinder.org/index.php/Testbench
and
https://sourceforge.net/p/vice-emu/code/HEAD/tree/testprogs/testbench/results/

To make the results even better, i am missing a few details, perhaps you can comment on these and/or add the missing features to the emulator, i will update the testbench accordingly.

- a command line option to reset everything to default. this is essential for getting reproducable testruns without interfering with whatever is currently saved to the settings
- a command line option to enable "cycle exact SID emulation" (this seems to be disabled by default for some reason)
- i couldn't find a list of the currently supported .crt types (so i can properly filter those that are not)
- i'd like to know which VICII variant you are aiming to emulate (there are subtle differences between older NMOS and never HMOS variants). (again this is needed to filter the tests that do not apply)

as a sidenote, i have seen on the wiki page that you hint on setting the drive speed (clock) from 0,9 to 1Mhz - this should really be the default. The drive always runs at 1Mhz, the C64 at 0,981 - a lot of fastloaders will fail if this is not the case :)

**Comment by abbruzze** [comment]
Hi Bob,
thanks so much for your work and for looking around into GitHubs repos 😀

Just in these days I'm working on the 1.7.0 final release: I'm gonna push
it in the next few days.
Because I added NTSC support but I've not done enough checking, I prefer to
not update the testbench's scripts to introduce the --ntsc option.
I noticed that some C128's tests failed, just for a particular handling of
PRG files on startup (that's caused the timeout) on the C128
implementation. I've fixed this on the 1.7.0.

As you suggested I added a --ignore-config-file option in order to ignore
the settings stored in the configuration file. Thanks.
To enable "cycle exact SID emulation" use --sid-cycle-exact, as you can
find in the hooks scripts.
I'll provide the list of supported CRT types; for now I can tell you that,
looking at the tests, you can skip the Nordic Power and the RR stuff.
The current VIC implementations are: 6569 & 6567R8 for C64.
About the wiki page: the wiki must be updated! There's no drive clock speed
adjustment, just a "max speed" checkbox (in the drive configuration panel)
that adjusts a little the drive speed; I adopted this workaround just to
run properly some damned fastloaders.

Thanks for now.
As soon as the 1.7.0 release will be ready I'll send you an email.

**Comment by mrdudz** [comment]
great :)

**Comment by abbruzze** [comment]
Hi Bob,
which JDK version did you use?

I was looking at the results you published and there are few that on my
laptop worked fine and I wondered what's happened; for example
selfttest/c64-pass.crt and Lorenz-2.15/src/ldaz,ldazx,ldaa.prg.
I repeated all the test suite and I noticed that I got a JVM crash in one
case: the crash produced a log file like this hs_err_pid5206.log where you
can find all the details about the run.
I think you had the same issue: can you check if you find the JVM error log
?
In my tests I used openjdk version "11.0.4" 2019-07-16.

**Comment by mrdudz** [comment]
```
$ java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)
```
i dont see any such log files

**Comment by mrdudz** [comment]
Oh i have another request - can you add an option to the c128 emulator (both c128 and c64 modes) that lets me select the videochip the exitscreenshot comes from?

**Comment by abbruzze** [comment]
Ok, I’ll work on this.
Because the VDC screen can have different resolutions, I wonder how the screenshot can be compared with a reference one.

**Comment by mrdudz** [comment]
that's a really good question.... i'll solve it when we actually have VDC tests with screenshots =)

**Comment by abbruzze** [comment]
Hi Bob,
I forgot it, but the option you asked is already there:
--vdcscreenshot <filePath>.

**Comment by mrdudz** [comment]
alright, will update the scripts, thx

**Comment by abbruzze** [comment]
Hi Andrew,
hope you are well.

I just published on GitHub the 1.7.0_b15 release of Kernal64: you can
download the installation zip at
https://github.com/abbruzze/kernal64/releases/download/v1.7.0/kernal64_install.zip.
The main page (https://github.com/abbruzze/kernal64) has not been updated
yet.

In attachment you can find:

   1. The hook scripts, updated for --ntsc and --vdcscreenshot
   2. The results for 1.7.0_b15 (with Oracle jdk 11.0.2)
   3. The test lists produced with the attached Make file

Notes:

   1. Below the list of supported carts:
      - ActionReplay
      - Final Cartridge III
      - Simon's Basic
      - Comal 80
      - Magic Desk
      - Dynamic
      - Game System
      - Warp Speed
      - Easy Flash
      - Ocean Type 1
      - Fun Play
      - Super Games
      - Epyx Fastload
      - Final Cartridge I
      - Super Snapshot V5
      - GMOD 2
      - Zaxxon
      - Mach 5
      - Page Fox
      - *CP/M*
      - *BeamRacer*
      - *DigiMax*
      - *SwiftLink*
      - *REU*
      - *GeoRAM*
   2. C128 supports only partially VICIIe, so I decided to skip tests about
   D030/2Mhz.

Ok, let me know when the new results will be available.
Thanks.

Bye.

**Comment by mrdudz** [comment]
Updated results where there since new year :) I will look into your recent additions and update again when i have the time to do so.

**Comment by mrdudz** [comment]
It seems the attachments you were talking about did not come through (probably github discards them?) - could you post patches against the recent svn version on the tracker? https://sourceforge.net/p/vice-emu/patches/

**Comment by abbruzze** [comment]
Hi Bob,
can you send me your email address ?
Contact me at abbruzze@gmail.com

Thanks.

**Comment by mrdudz** [comment]
ok, all merged, results updated

In the future if something has to be patched, please use the patches tracker and patch against the current trunk. cheers :)

**Comment by abbruzze** [comment]
Hi Bob,
thanks.

On note: as I wrote, on C128 VICIIe is partially supported, so I removed
these tests (Makefile):
| grep -v "2mhztest" \
| grep -v "2mhzVIC" \
| grep -v "d030tester" \

But I saw (from Testbench site) that these tests have been included as well.

**Comment by mrdudz** [comment]
Yeah, well - the whole point of the testbench is to show what works and what doesnt :) It makes sense to filter out things like unsupported cartridges.... But since the 2MHz mode and the VICIIe is pretty much a core component of the C128 skipping those tests doesnt make a lot of sense.
