### ISSUE TITLE
Beamracer - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ytmytm** [abbruzze/kernal64#14]
It's possible to trigger this exception with too large value of Bitmap Sequencer padding. If you take https://github.com/madhackerslab/beamracer-examples/blob/master/asm/demo_seq.s and change the line with padding hi byte https://github.com/madhackerslab/beamracer-examples/blob/ee338e42238e12a677cfa90c1e9d5f6abd36e1ad/asm/demo_seq.s#L40 from 0 into a large value, like
```
        MOV     VREG_PBS_PADDINGH, $30
```
the emulator will crash with out of bounds exception.

I think this is caused by adding the padding here: https://github.com/abbruzze/kernal64/blob/40a7e02981720e4be0e7283639ceb2959e15f6c3/Kernal64/src/ucesoft/cbm/peripheral/vic/coprocessor/VASYL.scala#L631
and then using it here:
https://github.com/abbruzze/kernal64/blob/40a7e02981720e4be0e7283639ceb2959e15f6c3/Kernal64/src/ucesoft/cbm/peripheral/vic/coprocessor/VASYL.scala#L699
without wrapping around 16-bit address boundary. That is done in the very next line, when step is added:
https://github.com/abbruzze/kernal64/blob/40a7e02981720e4be0e7283639ceb2959e15f6c3/Kernal64/src/ucesoft/cbm/peripheral/vic/coprocessor/VASYL.scala#L700

**Comment by abbruzze** [comment]
Thanks a lot for your reporting.
I've just pushed the fix.
