### ISSUE TITLE
windows line endings in unix scripts

### ISSUE THREAD

**Issue by ritschwumm** [abbruzze/kernal64#15]
after unpacking `kernal64_install.zip` from the 1.7.2b1 release, running `./k64.sh` on ubuntu fails with an error message `/bin/bash^M: bad interpreter: No such file or directory`. the reason for this seems to be that the script uses windows line endings (CRLF) instead of unix line endings (LF). it seems all the `.sh` files have this problem.

additionally, it would be nice if the scripts could have the executable bit set so i don't have to set it manually after unpacking.

**Comment by ritschwumm** [comment]
just saw this _should_ be fixed in https://github.com/abbruzze/kernal64/commit/eeee2167ff1d2b9fcd809a8168b91a328d3168ee#diff-8e83f6c754af0debd3e2461e385e3eb91b477f95c64de654fb5561754b0da4f7 already...

**Comment by abbruzze** [comment]
I fixed both, CRLF and executable permissions.
You can download the fix from the 1.7.2.b1 release (inside you will find the 1.7.2.b2): https://github.com/abbruzze/kernal64/releases/tag/v1.7.2b1.

Thanks.

**Comment by ritschwumm** [comment]
thank you very much :)
