### ISSUE TITLE
Scripts for running emulator on Linux do not handle spaces (+solution)

### ISSUE THREAD

**Issue by zzarko** [abbruzze/kernal64#21]
If I try to use for example --run-file command line option with a name that contains spaces, it will try to load with only last part of the name, i.e.
--run-file "afterburner +2"
will inside emulator try to load
load"+2",8,1

Solution is simple, just change last parameter in bash scripts in the last line from
`$*`
to
`"$@"`
(with quotes!)

**Comment by abbruzze** [comment]
Sorry, for the delay.
You're right!
Thanks for the suggestion: I will include it in the cbm2 branch and at the first merge on main.

**Comment by zzarko** [comment]
No problem, I'm glad I could help! Thanks for the great emulator!
