### ISSUE TITLE
Q: how integrate it with vscode

### ISSUE THREAD

**Issue by ch0mik** [abbruzze/kernal64#22]
Hi,

Great JOB!

I want to develop software for Wic64 and I want integrate kernal64 to run/debug software in vscode - how doit ?

Regards
Pawel

**Comment by abbruzze** [comment]
Hi, thanks.
What do you mean for integrate ?
What would you like to do with vscode and Kernal64 ?

**Comment by ch0mik** [comment]
@abbruzze  hi, Integrate to debug software under VS Code and Kernal64 (I want to write soft for WiC64)

Regards
Pawel
