### ISSUE TITLE
Nice work.. but can't run freespin

### ISSUE THREAD

**Issue by Zibri** [abbruzze/kernal64#23]
I noticed the option freespin cable in the menu.
I enabled it the loaded freespin...
What else should I need to do to make it work?

**Comment by abbruzze** [comment]
Hi,
the free spin option enables the emulation of the free spin demo (see http://www.quiss.org/freespin/).
Download the demo at http://www.quiss.org/freespin/freespin.d64 and run it.
When it is asked to open/close the driver's lever, re-insert the same demo disk, then enable the free spin option.
When the demo finishes uncheck the "freespin cable enabled"
