### ISSUE TITLE
[Feature] Restart Kernal64 with same PRG

### ISSUE THREAD

**Issue by shazz** [abbruzze/kernal64#7]
Hi,

In case you think this is a good idea, that would be nice to have a keyboard shortcut to
1. Reset the emulator
2. Reload the last selected PRG (else, do nothing)
3. Run it again automatically 

(mostly like `k64 my.prg` is doing when started from scratch)

Just because I spend my time debugging and I do `alt-r`, `alt-g`, `mouse click` (as the PRG is not selected by default), `Enter`, `RUN`

Thanks !

**Comment by abbruzze** [comment]
Done.
Check in the BeamRacer branch. Use CTRL+ALT+R to reset and restore the last PRG.
Take a look at Settings->VIC->VIC's display effects...

**Comment by shazz** [comment]
Thanks for updating the branch I was on!
Works perfectly, so better to debug :+1: 

Not sure the screen rotation is that useful but this is funny :)
