### ISSUE TITLE
[Feature] Screen borders

### ISSUE THREAD

**Issue by shazz** [abbruzze/kernal64#9]
Hi again,

I'm now using kernal64 as my main testing and debugging tool and it would be great if how much of the borders (top, bottom and side) can be shown (default or full) so that I can check how much time I'm consuming "in the borders" and where my sprites appear.

Thanks!

**Comment by abbruzze** [comment]
I added under VIC menù the option to draw (or not draw) the borders; it's the best I can do quickly.
Thanks.
